### ISSUE TITLE
Rendering Hindi text

### ISSUE THREAD

**Issue by benoitkugler** [go-text/render#11]
Rendering the string नमस्ते with the [Mangal](https://hindi-fonts.com/fonts/mangal-regular) font result in 
![hindi](https://github.com/go-text/render/assets/31929422/d16c0ab5-4dea-455b-a3dd-f621baa0b9c2)

whereas Harfbuzz yields 
![test](https://github.com/go-text/render/assets/31929422/4dcc352b-c67e-42d4-9266-959a298e1325)

Discovered in https://github.com/golang/go/issues/65048

**Comment by benoitkugler** [comment]
Actually, using `DrawShapedRunAt` with the correct `Script` fixes the issue.

So the fix is about including proper script information into `DrawString`. One way to do it would be to include a `shaping.Segmenter` instance in the `Renderer` and use it to properly split the input string, then call `DrawShapedRunAt` for each run created. 
@andydotxyz What do you think ? If that sound sensible, I can send a PR.

**Comment by MayankFawkes** [comment]
i did some other testing as well in hindi we also have some other kind of fonts like ``Kruti Dev`` and it is working with it.
[font url](https://hindi-fonts.com/fonts/kruti-dev-010-regular) with text `ueLrs` , the problem seems to be with just the unicodes 

```go
data, _ := os.Open("assets/fonts/k010.ttf")
f, _ := font.ParseTTF(data)

r := &render.Renderer{
  FontSize: 48,
  Color:    color.Black,
}
str := "ueLrs"
r.DrawString(str, img, f)
```

output

![image](https://github.com/go-text/render/assets/43340190/2d917b76-f6ff-47d0-bc70-0ad848d5426f)

**Comment by benoitkugler** [comment]
> i did some other testing as well in hindi we also have some other kind of fonts like `Kruti Dev` and it is working with it.

Thank you for the tests.

**Comment by andydotxyz** [comment]
> Actually, using `DrawShapedRunAt` with the correct `Script` fixes the issue.
> 
> So the fix is about including proper script information into `DrawString`. One way to do it would be to include a `shaping.Segmenter` instance in the `Renderer` and use it to properly split the input string, then call `DrawShapedRunAt` for each run created. @andydotxyz What do you think ? If that sound sensible, I can send a PR.

That sounds sensible. I was aware we would need to pass in some more hinting but did not have it working locally yet sorry.
What you propose sounds good and should enable to helper methods to function just as smoothly in these complex scenarios :).
