### ISSUE TITLE
Noto Color Emoji Font weird offset

### ISSUE THREAD

**Issue by montovaneli** [go-text/render#15]
When using this bundled font in Fyne, replacing the standard emoji font, the render acts strangely, as if the font was cut off. 

![image](https://github.com/go-text/render/assets/25851559/bcd3a30b-14b8-4977-9fb6-a51bed7e95c8)

I decided to investigate and after analyzing the font in FontLab, I realized the emojis for this font were not SVGs but bitmaps. So I came across this line in the render.go file:

```
case api.GlyphBitmap: 
_ = r.drawBitmap(g, format, img, xPos, yPos)
```

After some tests to understand how yPos works, I changed it to 0 and the problem was completely solved (tested on Windows and Mac). 

![image](https://github.com/go-text/render/assets/25851559/5128fac2-a9de-47fd-af7f-76a25161b426)

I don't know if I was just super lucky, but I thought it was worth reporting here.

**Comment by andydotxyz** [comment]
Ah, possibly - I tested most with the SVG. However the tests show baseline alignment so this is confusing.
Can you confirm the font file download so I can drop it in and see what changed?

**Comment by montovaneli** [comment]
> Ah, possibly - I tested most with the SVG. However the tests show baseline alignment so this is confusing. Can you confirm the font file download so I can drop it in and see what changed?

Sure, https://github.com/googlefonts/noto-emoji/blob/main/fonts/NotoColorEmoji.ttf

**Comment by andydotxyz** [comment]
Thanks for that. I think maybe you got lucky - when I try the same change with the same font but with a different font size perhaps I get the wrong baseline:

![Uploading emoji.png…]()

**Comment by andydotxyz** [comment]
Thanks for that. I think maybe you got lucky - when I try the same change with the same font but with a different font size perhaps I get the wrong baseline:

![emoji](https://github.com/go-text/render/assets/294436/1535c127-208c-41f8-85ab-373cd12cd8d5)

**Comment by andydotxyz** [comment]
Ah yes, `0` aligns it to the top of the output image which is not always correct (multiline, padding etc).
I have opened a PR that I think does the correct math, though I am not certain why bitmap emoji seems 25% larger than SVG emoji for same font size...
