### ISSUE TITLE
Tag version 0.1.1 with the bitmap index-out-of-bounds fix

### ISSUE THREAD

**Issue by dweymouth** [go-text/render#19]
This will allow Fyne, Gio, etc to build against the version with the bug fixed :)

**Comment by andydotxyz** [comment]
I'd rather see if we can get to the bottom of the other issue we are working on (https://github.com/go-text/typesetting/issues/166) and tag it when we have more testing of both.

**Comment by andydotxyz** [comment]
Done, sorry for the delay
